---
title: "Namenskonventionen"
---

## Übersicht

|Baustein|Auflage|Version|Runtime|Project|
|--------|-------|-------|-------|----|
|`B1A`, `B1B`, ..., `S4B`|`edition-1` oder `edition-2`| `V01` oder `V02` | `9.9.0` oder `10.0.0`|`*_1.zip`, `*_2.zip`, ...|


Anmerkungen:

* *CBA-ItemBuilder*Projektdateien in unterschiedlichen *Runtime*-Versionen sind inhaltsäquivalent.
* *Version* identifiziert die inhaltliche Version eines Bausteins (gleiches Fördermaterial)
* *Auflage* identifiziert die konzeptuell veränderten Bausteine (anderes Fördermaterial)


## Struktur des Repository  

* Branch: `main`: OER Inhalte
* Branch: `gh-pages`: Ausgabe als Website
  - Abrufbar unter https://kroehne.github.io/msk-oc/
* Branch: `quarto`: R-/Quarto-Project zur Erstellung der Website 
  - Benötigt den Inahtld es Branch `main` im Verzeichnis `_content/` 

### CBA ItemBuilder Projekt-Dateien

* Auflage (1. Auflage = `edition-1`,  2. Auflage = `edition-2`, ... ) 
  - Version (`V01`, `V02`, ...)  
    - Baustein (`msk_b1_a`, `msk_b1_b`, ...)  
      - Runtime (`9.9.0`, `10.0.0`, ...) 

### Codebooks

Codebooks aus der Programmierung von `alea.schule`: 

* Auflage (1. Auflage = `edition-1`,  2. Auflage = `edition-2`, ... ) 
  - Version (`V01`, `V02`, ...)  
    - Baustein (`msk_b1_a`, `msk_b1_b`, ...)  

