---
title: "S1A - LÄNGEN UND FLÄCHENINHALTE VERSTEHEN"
---

*Ich kann mir Längen vorstellen und mit geeigenten Messgeräten messen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s1_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_a/msk_s1_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Längen kennen, schätzen und messen
	 - a) Miss die Linie und schreibe ihre Länge auf.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_a_1.zip](../oer/edition-1/V01/9.9.0/msk_s1_a/msk_s1_a_1/msk_s1_a_1.zip) 
:::
<hr noshade/>

### 1b (1), 1b (2), 1b (3), 1c (1), 1c (2) und 1c (3)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_a/msk_s1_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Längen kennen, schätzen und messen
	 - b) Welches Maß passt besser, um die Längen anzugeben? Kreuze an.
	 - c) (1) Nenne drei Gegenstände, die 1m lang, breit oder hoch sind.
	 - c) (2) Nenne drei Gegenstände, die 1m lang, breit oder hoch sind.
	 - c) (3) Nenne drei Gegenstände, die 1m lang, breit oder hoch sind.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_a_2.zip](../oer/edition-1/V01/9.9.0/msk_s1_a/msk_s1_a_2/msk_s1_a_2.zip) 
:::
<hr noshade/>

### 2a (1) und 2a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_a/msk_s1_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Längen vergleichen und mit Längen rechnen
	 - a) Ein durchschnittlicher Erwachsener ist etwa 1,70m groß. Wie groß sind die Tiere?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_a_3.zip](../oer/edition-1/V01/9.9.0/msk_s1_a/msk_s1_a_3/msk_s1_a_3.zip) 
:::
<hr noshade/>

### 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_a/msk_s1_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Längen vergleichen und mit Längen rechnen
	 - b) Wie lang sind die beiden Linien zusammen?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_a_4.zip](../oer/edition-1/V01/9.9.0/msk_s1_a/msk_s1_a_4/msk_s1_a_4.zip) 
:::
<hr noshade/>

### 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_a/msk_s1_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Längen vergleichen und mit Längen rechnen
	 - c) Eine Tasse ist etwa 10 cm hoch. Wie hoch sind 11 Tassen übereinander gestapelt?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_a_5.zip](../oer/edition-1/V01/9.9.0/msk_s1_a/msk_s1_a_5/msk_s1_a_5.zip) 
:::
<hr noshade/>

