---
title: "N7A - SCHRIFTLICH ADDIEREN UND SUBTRAHIEREN"
---

*Ich kann schriftlich addieren und das Rechenverfahren erklären* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n7_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a und 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Addition ohne Übertrag
	 - a)
	 - b)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_a_1.zip](../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_1/msk_n7_a_1.zip) 
:::
<hr noshade/>

### 2a, 2b und 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Addition mit Übertrag
	 - a)
	 - b)
	 - c)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_a_2.zip](../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_2/msk_n7_a_2.zip) 
:::
<hr noshade/>

### 2d (1) und 2d (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Addition mit Übertrag
	 - d) (1) Sarah rechnet die Aufgabe 427+456. Beschreibe, was sie macht.
	 - d) (2) Sarah rechnet die Aufgabe 427+457. Beschreibe, was sie macht.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_a_3.zip](../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_3/msk_n7_a_3.zip) 
:::
<hr noshade/>

### 3a, 3b und 3c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Addition mit der Null
	 - a)
	 - b)
	 - c)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_a_4.zip](../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_4/msk_n7_a_4.zip) 
:::
<hr noshade/>

### 4a (1), 4a (2), 4b (1) und 4b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Addition mit unterschiedlicher Stellenzahl
	 - a) Rechne schriftlich untereinander.
	 - b) Rechne schriftlich untereinander.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_a_5.zip](../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_5/msk_n7_a_5.zip) 
:::
<hr noshade/>

### 4a (1), 4a (2), 4b (1) und 4b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Addition mit unterschiedlicher Stellenzah
	 - a) Rechne schriftlich untereinander.
	 - b) Rechne schriftlich untereinander.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_a_5.zip](../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_5/msk_n7_a_5.zip) 
:::
<hr noshade/>

### 4c (1) und 4c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Addition mit unterschiedlicher Stellenzahl
	 - c) Rechne schriftlich untereinander.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_a_6.zip](../oer/edition-1/V01/9.9.0/msk_n7_a/msk_n7_a_6/msk_n7_a_6.zip) 
:::
<hr noshade/>

