---
title: "N6B - MULTIPLIZIEREN UND DIVIDIEREN"
---

*Ich kann sicher multiplizieren und Rechenwege erklären* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n6_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1), 1a (2), 1b (1) und 1b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Multiplizieren bis 100
	 - NA
	 - Beschreibe, wie du die Aufgabe gelöst hast:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_b_1.zip](../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_1/msk_n6_b_1.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2), 2b (1) und 2b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Multiplizieren bis 200
	 - NA
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_b_2.zip](../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_2/msk_n6_b_2.zip) 
:::
<hr noshade/>

### 2c (1) und 2c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Multiplizieren bis 200
	 - NA
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_b_3.zip](../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_3/msk_n6_b_3.zip) 
:::
<hr noshade/>

### 3 (1) und 3 (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Multiplizieren bis 400
	 - NA
	 - Beschreibe, wie du die Aufgabe gelöst hast:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_b_4.zip](../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_4/msk_n6_b_4.zip) 
:::
<hr noshade/>

### 4a (1), 4a (1)(1), 4a (2), 4a (2)(1), 4a(3) und 4a(3)(1)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Multiplizieren bis 400
	 - a) (1)
	 - NA
	 - a) (2)
	 - a) (3)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_b_5.zip](../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_5/msk_n6_b_5.zip) 
:::
<hr noshade/>

### 4b (1), 4b (2) (1), 4b (2)(2), 4b (3) (1) und 4b (3)(2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Multiplizieren bis 400
	 - b) (1) Rechne die Aufgaben mit dem Malkreuz. Kreuze an:
	 - NA
	 - b) (2) Rechne die Aufgaben mit dem Malkreuz. 
	 - b) (3) Rechne die Aufgaben mit dem Malkreuz. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_b_6.zip](../oer/edition-1/V01/9.9.0/msk_n6_b/msk_n6_b_6/msk_n6_b_6.zip) 
:::
<hr noshade/>

