---
title: "S4B - DIAGRAMME VERSTEHEN UND NUTZEN"
---

*Ich kann Daten in Diagrammen darstellen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s4_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s4_b/msk_s4_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Daten in Säulendiagramme übertragen
	 - Ergänze im Diagramm die fehlenden Säulen und Wörter.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s4_b_1.zip](../oer/edition-1/V01/9.9.0/msk_s4_b/msk_s4_b_1/msk_s4_b_1.zip) 
:::
<hr noshade/>

### 2
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s4_b/msk_s4_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Aufbau in Säulendiagrammen
	 - Ergänze die fehlenden Zahlen an der 2. Achse.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s4_b_2.zip](../oer/edition-1/V01/9.9.0/msk_s4_b/msk_s4_b_2/msk_s4_b_2.zip) 
:::
<hr noshade/>

### 3a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s4_b/msk_s4_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Säulendiagramme zeichnen
	 - a) Warum ist das Säulendiagramm von Tim besonders gut gelungen?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s4_b_3.zip](../oer/edition-1/V01/9.9.0/msk_s4_b/msk_s4_b_3/msk_s4_b_3.zip) 
:::
<hr noshade/>

### 3b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s4_b/msk_s4_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Säulendiagramme zeichnen
	 - b) Zeichne ein Säulendiagramm zu der Tabelle mit den Lieblingsfächern der Klasse 5d.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s4_b_4.zip](../oer/edition-1/V01/9.9.0/msk_s4_b/msk_s4_b_4/msk_s4_b_4.zip) 
:::
<hr noshade/>

