---
title: "N2C - ZAHLEN ORDNEN UND VERGLEICHEN"
---

*Ich kann Nachbarzahlen zu Zahlen angeben und in Schritten zählen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n2_c 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_c/msk_n2_c_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Nachbar-Einer und Nachbar-Zehner
	 - Zwischen welchen Einern und Zehnern steht die Zahl? Trage ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_c_1.zip](../oer/edition-1/V01/9.9.0/msk_n2_c/msk_n2_c_1/msk_n2_c_1.zip) 
:::
<hr noshade/>

### 2a und 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_c/msk_n2_c_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 In Schritten zählen
	 - a) Zeichne Zweihunderterschritte vorwärts und schreibe die Zahlen bis 1000 auf.
	 - b) Zeichne Zweihunderterschritte rückwärts und schreibe die Zahl auf.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_c_2.zip](../oer/edition-1/V01/9.9.0/msk_n2_c/msk_n2_c_2/msk_n2_c_2.zip) 
:::
<hr noshade/>

### 3a, 3b und 3c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_c/msk_n2_c_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Zahlenreihen
	 - a) Ergänze die Zahlenreihen.
	 - b) Ergänze die Zahlenreihen.
	 - c) Ergänze die Zahlenreihen.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_c_3.zip](../oer/edition-1/V01/9.9.0/msk_n2_c/msk_n2_c_3/msk_n2_c_3.zip) 
:::
<hr noshade/>

### 3d
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_c/msk_n2_c_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Zahlenreihen
	 - d) Ergänze die Zahlenreihen. In welchen Schritten wurde hier gezählt?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_c_4.zip](../oer/edition-1/V01/9.9.0/msk_n2_c/msk_n2_c_4/msk_n2_c_4.zip) 
:::
<hr noshade/>

