---
title: "B3B - BRÜCHE UND PROZENTE ORDNEN"
---

*Ich kann Brüche und Prozente vergleichen und der Größe nach ordnen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_b3_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1) und 1a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Anteile in Bildern und Situationen vergleichen
	 - a) Tim fragt: "Was ist größer: 1/7 oder 1/8? Wähle aus und erkläre Tim, welcher Anteil größer ist.
	 - Erklärung:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b3_b_1.zip](../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_1/msk_b3_b_1.zip) 
:::
<hr noshade/>

### 1b (1) und 1b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Anteile in Bildern und Situationen vergleichen
	 - b) Ist 5/6 größer oder kleiner als 3/4 oder sind beide gleich groß? Zeige mit einem Bild.
	 - b) Bild
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b3_b_2.zip](../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_2/msk_b3_b_2.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2) und 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Brüche vergleichen mit Situationen, Bildern, Zahlbeziehungen
	 - a) "Kleiner als (<)", "größer als (>)" oder "genauso groß wie (=)" Wähle aus:
	 - b) Erkläre deine Lösung zu a) (2).
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b3_b_3.zip](../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_3/msk_b3_b_3.zip) 
:::
<hr noshade/>

### 3a (1) und 3a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Brüche und Prozente ordnen
	 - a) "Kleiner als (<)", "größer als (>)" oder "genauso groß wie (=)" ? Trage ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b3_b_4.zip](../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_4/msk_b3_b_4.zip) 
:::
<hr noshade/>

### 3b (1) und 3b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Brüche und Prozente ordnen
	 - b) "Kleiner als (<)", "größer als (>)" oder "genauso groß wie (=)" ? Trage ein und erkläre.
	 - Erklärung:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b3_b_5.zip](../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_5/msk_b3_b_5.zip) 
:::
<hr noshade/>

### 3c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Brüche und Prozente ordnen
	 - Hat Kati Recht? Kreuze an.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b3_b_6.zip](../oer/edition-1/V01/9.9.0/msk_b3_b/msk_b3_b_6/msk_b3_b_6.zip) 
:::
<hr noshade/>

