---
title: "N5A - ADDIEREN UND SUBTRAHIEREN"
---

*Ich kann addieren und subtrahieren und die Rechenwege erklären* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n5_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Addieren
	 - a) Rechne aus. Trage dazu in jedes Feld etwas ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n5_a_1.zip](../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_1/msk_n5_a_1.zip) 
:::
<hr noshade/>

### 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Addieren
	 - b) Rechne aus. Trage dazu in jedes Feld etwas ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n5_a_2.zip](../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_2/msk_n5_a_2.zip) 
:::
<hr noshade/>

### 1c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Addieren
	 - c) Rechne aus. Trage dazu in jedes Feld etwas ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n5_a_3.zip](../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_3/msk_n5_a_3.zip) 
:::
<hr noshade/>

### 1d
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Addieren
	 - d) Rechne aus. Trage dazu in jedes Feld etwas ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n5_a_4.zip](../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_4/msk_n5_a_4.zip) 
:::
<hr noshade/>

### 2a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Subtrahieren
	 - a) Rechne aus. Trage dazu in jedes Feld etwas ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n5_a_5.zip](../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_5/msk_n5_a_5.zip) 
:::
<hr noshade/>

### 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Subtrahieren
	 - b) Rechne aus. Trage dazu in jedes Feld etwas ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n5_a_6.zip](../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_6/msk_n5_a_6.zip) 
:::
<hr noshade/>

### 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_7/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Subtrahieren
	 - c) Rechne aus. Trage dazu in jedes Feld etwas ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n5_a_7.zip](../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_7/msk_n5_a_7.zip) 
:::
<hr noshade/>

### 2d
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_8/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Subtrahieren
	 - d) Rechne aus. Trage dazu in jedes Feld etwas ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n5_a_8.zip](../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_8/msk_n5_a_8.zip) 
:::
<hr noshade/>

### 3
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_9/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Addieren und Subtrahieren
	 - Welche Plus- und welche Minus-Aufgabe passt zu dem Zahlenstrahl? Trage ein. Rechne aus. Trage dazu in jedes Feld etwas ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n5_a_9.zip](../oer/edition-1/V01/9.9.0/msk_n5_a/msk_n5_a_9/msk_n5_a_9.zip) 
:::
<hr noshade/>

