---
title: "S1D - LÄNGEN UND FLÄCHENINHALTE VERSTEHEN"
---

*Ich kann Längen-, Flächen-, und Gewichtsmaße vergleichen und ordnen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s1_d 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1), 1a (2), 1b (2), 1b (3) und 1b (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_d/msk_s1_d_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Längenmaße umrechnen, vergleichen und ordnen
	 - a) (1) Beantworte die folgenden Fragen:
	 - a) (2) Beantworte die folgenden Fragen:
	 - b) (2) Beantworte die folgenden Fragen:
	 - b) (3) Beantworte die folgenden Fragen:
	 - b) (4) Beantworte die folgenden Fragen:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_d_1.zip](../oer/edition-1/V01/9.9.0/msk_s1_d/msk_s1_d_1/msk_s1_d_1.zip) 
:::
<hr noshade/>

### 2
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_d/msk_s1_d_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Flächenmaße umrechnen, vergleichen und ordnen
	 - Kreuze die größte Fläche an:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_d_2.zip](../oer/edition-1/V01/9.9.0/msk_s1_d/msk_s1_d_2/msk_s1_d_2.zip) 
:::
<hr noshade/>

### 3
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_d/msk_s1_d_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Gewichtsmaße umrechnen, vergleichen und ordnen
	 - Für eine große Pizza braucht man: 1,2 kg Teig, 700 g Tomatensauce, 400 g geriebenen Käse und 8 g Oregano. Wie viel wiegen die Zutaten zusammen? Schreibe deinen Lösungsweg und dein Ergebnis auf.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_d_3.zip](../oer/edition-1/V01/9.9.0/msk_s1_d/msk_s1_d_3/msk_s1_d_3.zip) 
:::
<hr noshade/>

### 4 (1), 4 (2) und 4 (3)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_d/msk_s1_d_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Wissenswertes zum Umrechnen
	 - (1) Vervollständige die folgenden Sätze:
	 - (2) Vervollständige die folgenden Sätze:
	 - (3) Vervollständige die folgenden Sätze:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_d_4.zip](../oer/edition-1/V01/9.9.0/msk_s1_d/msk_s1_d_4/msk_s1_d_4.zip) 
:::
<hr noshade/>

