---
title: "N3A - ADDITION UND SUBTRAKTION VERSTEHEN"
---

*Ich kann Additions- und Subtraktionsaufgaben zu Situationen finden und umgekehrt* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n3_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Additions- und Subtraktions-Aufgaben mit Würfelmaterial
	 - a) In dem folgenden Video wird mit Hilfe von Einer-Würfeln und Zehner-Stangen eine Rechenaufgabe gelegt. Schreibe die Aufgabe auf und rechne sie aus
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n3_a_1.zip](../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_1/msk_n3_a_1.zip) 
:::
<hr noshade/>

### 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Additions- und Subtraktions-Aufgaben mit Würfelmaterial
	 - b) In dem folgenden Video wird mit Hilfe von Einer-Würfeln und Zehner-Stangen eine Rechenaufgabe gelegt. Schreibe die Aufgabe auf und rechne sie aus
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n3_a_2.zip](../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_2/msk_n3_a_2.zip) 
:::
<hr noshade/>

### 1c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Additions- und Subtraktions-Aufgaben mit Würfelmaterial
	 - c) In dem folgenden Video wird mit Hilfe von Einer-Würfeln und Zehner-Stangen eine Rechenaufgabe gelegt. Schreibe die Aufgabe auf und rechne sie aus
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n3_a_3.zip](../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_3/msk_n3_a_3.zip) 
:::
<hr noshade/>

### 1d
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Additions- und Subtraktions-Aufgaben mit Würfelmaterial
	 - d) In dem folgenden Video wird mit Hilfe von Einer-Würfeln und Zehner-Stangen eine Rechenaufgabe gelegt. Schreibe die Aufgabe auf und rechne sie aus
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n3_a_4.zip](../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_4/msk_n3_a_4.zip) 
:::
<hr noshade/>

### 2a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Additions- und Subtraktions-Aufgaben mit gezeichnetem Würfelmaterial
	 - a) Welche Plus-Aufgabe wurde hier gezeichnet? Trage ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n3_a_5.zip](../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_5/msk_n3_a_5.zip) 
:::
<hr noshade/>

### 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Additions- und Subtraktions-Aufgaben mit gezeichnetem Würfelmaterial
	 - b) Welche Minus-Aufgabe wurde hier gezeichnet? Trage ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n3_a_6.zip](../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_6/msk_n3_a_6.zip) 
:::
<hr noshade/>

### 3
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_7/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Additions- und Subtraktions-Aufgaben im Kopf
	 - Berechne im Kopf.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n3_a_7.zip](../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_7/msk_n3_a_7.zip) 
:::
<hr noshade/>

### 4a und 4b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_8/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Additions- und Subtraktions-Aufgaben am Zahlenstrahl
	 - Welche Aufgaben passen zu dem Zahlenstrahl? Trage ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n3_a_8.zip](../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_8/msk_n3_a_8.zip) 
:::
<hr noshade/>

### 5
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_9/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 5 Additions- und Subtraktions-Rechengeschichten
	 - Erfinde eine eigene Textaufgabe zu der Minus-Aufgabe 68-41.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n3_a_9.zip](../oer/edition-1/V01/9.9.0/msk_n3_a/msk_n3_a_9/msk_n3_a_9.zip) 
:::
<hr noshade/>

