---
title: "D4A - MULTIPLIZIEREN UND DIVIDIEREN VON DEZIMALZAHLEN"
---

*Ich kann Dezimalzahlen mit Zehnerzahlen multiplizieren und dividieren* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_d4_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1), 1a (2), 1b (1), 1b (2), 1c (1) und 1c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d4_a/msk_d4_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Dezimalzahlen mit Zehnerzahlen multiplizieren
	 - a) Rechne die Aufgabe aus. Schreibe deinen Rechenweg auf.
	 - b) Rechne die Aufgabe aus. Schreibe deinen Rechenweg auf.
	 - c) Rechne die Aufgabe aus. Schreibe deinen Rechenweg auf.
	 - c)  Rechne die Aufgabe aus. Schreibe deinen Rechenweg auf.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d4_a_1.zip](../oer/edition-1/V01/9.9.0/msk_d4_a/msk_d4_a_1/msk_d4_a_1.zip) 
:::
<hr noshade/>

### 2a (1) und 2a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d4_a/msk_d4_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Dezimalzahlen durch Zehnerzahlen dividieren
	 - a)  Rechne die Aufgaben aus. Schreibe deinen Rechenweg auf.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d4_a_2.zip](../oer/edition-1/V01/9.9.0/msk_d4_a/msk_d4_a_2/msk_d4_a_2.zip) 
:::
<hr noshade/>

### 2b (1) und 2b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d4_a/msk_d4_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Dezimalzahlen durch Zehnerzahlen dividieren
	 - b) Rechne die Aufgaben aus. Schreibe deinen Rechenweg auf.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d4_a_3.zip](../oer/edition-1/V01/9.9.0/msk_d4_a/msk_d4_a_3/msk_d4_a_3.zip) 
:::
<hr noshade/>

