---
title: "B2C - GLEICHWERTIGKEIT VERSTEHEN"
---

*Ich kann Brüche und Prozente ineinander umwandeln* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_b2_c 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1), 1a (2) und 1a (3)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_c/msk_b2_c_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Brüche in Hundertstelbrüche umwandeln
	 - a) (1) Erweitere die Brüche auf einen Bruch mit Nenner 100.
	 - a) (2) Erweitere die Brüche auf einen Bruch mit Nenner 100.
	 - a) (3) Erweitere die Brüche auf einen Bruch mit Nenner 100.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_c_1.zip](../oer/edition-1/V01/9.9.0/msk_b2_c/msk_b2_c_1/msk_b2_c_1.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2), 2a (3) und 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_c/msk_b2_c_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Brüche und Prozente umwandeln
	 - a) (1) Schreibe als Prozent.
	 - a) (2) Schreibe als Prozent.
	 - a) (3) Schreibe als Prozent.
	 - b) Beschreibe, wie du (3) gerechnet hast.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_c_2.zip](../oer/edition-1/V01/9.9.0/msk_b2_c/msk_b2_c_2/msk_b2_c_2.zip) 
:::
<hr noshade/>

### 2c (1), 2c (2), 2c (3) und 2c (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_c/msk_b2_c_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Brüche und Prozente umwandeln
	 - c) (1) Gib immer zwei verschiedene Brüche an, die der Prozentzahl entsprechen.
	 - c) (2) Gib immer zwei verschiedene Brüche an, die der Prozentzahl entsprechen.
	 - c) (3) Gib immer zwei verschiedene Brüche an, die der Prozentzahl entsprechen.
	 - c) (4) Gib immer zwei verschiedene Brüche an, die der Prozentzahl entsprechen.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_c_3.zip](../oer/edition-1/V01/9.9.0/msk_b2_c/msk_b2_c_3/msk_b2_c_3.zip) 
:::
<hr noshade/>

### 2d (1), 2d (2) und 2d (3)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_c/msk_b2_c_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Brüche und Prozente umwandeln
	 - d) (1) Wandle in Prozent um und markiere ungefähr am Prozentstreifen.
	 - d) (2) Wandle in Prozent um und markiere ungefähr am Prozentstreifen.
	 - d) (3) Wandle in Prozent um und markiere ungefähr am Prozentstreifen.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_c_4.zip](../oer/edition-1/V01/9.9.0/msk_b2_c/msk_b2_c_4/msk_b2_c_4.zip) 
:::
<hr noshade/>

