---
title: "S2A - SACHAUFGABEN LÖSEN"
---

*Ich kann bei Sachaufgaben sinnvoll überschlagen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s2_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1 (1), 1 (2), 1 (3) und 1 (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s2_a/msk_s2_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Wie viel ungefähr?
	 - (1) Mache einen Überschlag und rechne ihn aus.
	 - (2) Mache einen Überschlag und rechne ihn aus.
	 - (3) Mache einen Überschlag und rechne ihn aus.
	 - (4) Mache einen Überschlag und rechne ihn aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s2_a_1.zip](../oer/edition-1/V01/9.9.0/msk_s2_a/msk_s2_a_1/msk_s2_a_1.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2), 2b (1) und 2b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s2_a/msk_s2_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Kann das stimmen?
	 - a) Überschlage. Kreuze dann an und erkläre deinen Lösungsweg.
	 - b) Überschlage. Kreuze dann an und erkläre deinen Lösungsweg.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s2_a_2.zip](../oer/edition-1/V01/9.9.0/msk_s2_a/msk_s2_a_2/msk_s2_a_2.zip) 
:::
<hr noshade/>

### 3a (1), 3a (2), 3b (1) und 3b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s2_a/msk_s2_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Reicht das Geld?
	 - a) Überschlage. Kreuze dann an und erkläre deinen Lösungsweg.
	 - b) Überschlage. Kreuze dann an und erkläre deinen Lösungsweg.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s2_a_3.zip](../oer/edition-1/V01/9.9.0/msk_s2_a/msk_s2_a_3/msk_s2_a_3.zip) 
:::
<hr noshade/>

### 4a (1), 4a (2), 4b (1) und 4b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s2_a/msk_s2_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Ungefähr oder genau?
	 - a) Wann reicht es zu überschlagen und wann ist es wichtig, genau zu rechnen? Kreuze an und erkläre. Du musst bei dieser Aufgabe nichts ausrechnen.
	 - b) Wann reicht es zu überschlagen und wann ist es wichtig, genau zu rechnen? Kreuze an und erkläre. Du musst bei dieser Aufgabe nichts ausrechnen.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s2_a_4.zip](../oer/edition-1/V01/9.9.0/msk_s2_a/msk_s2_a_4/msk_s2_a_4.zip) 
:::
<hr noshade/>

