---
title: "S6C - MIT PROZENTEN RECHNEN"
---

*Ich kann mit verschiedenen Textaufgaben zur Prozentrechnung umgehen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s6_c 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s6_c/msk_s6_c_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Verschiedene Textaufgaben unterscheiden
	 - a) Was ist in den textaufgaben jeweils gesucht? Ordne zu.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s6_c_1.zip](../oer/edition-1/V01/9.9.0/msk_s6_c/msk_s6_c_1/msk_s6_c_1.zip) 
:::
<hr noshade/>

### 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s6_c/msk_s6_c_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Verschiedene Textaufgaben unterscheiden
	 - b) Löse die folgende Textaufgabe. Ergänze dazu den Prozentstreifen.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s6_c_2.zip](../oer/edition-1/V01/9.9.0/msk_s6_c/msk_s6_c_2/msk_s6_c_2.zip) 
:::
<hr noshade/>

### 2
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s6_c/msk_s6_c_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Textaufgaben selbst erstellen
	 - Schreibe zu der Aufgabe ,,70 % von 200 sind 140" eine eigene Textaufgabe.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s6_c_3.zip](../oer/edition-1/V01/9.9.0/msk_s6_c/msk_s6_c_3/msk_s6_c_3.zip) 
:::
<hr noshade/>

### 3a (1) und 3a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s6_c/msk_s6_c_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Schwierige Textaufgaben bearbeiten
	 - a) Fülle die Lücken aus und notiere deine Rechnung. Gehe von einer Mehrwertsteuer von 19 % aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s6_c_4.zip](../oer/edition-1/V01/9.9.0/msk_s6_c/msk_s6_c_4/msk_s6_c_4.zip) 
:::
<hr noshade/>

### 3b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s6_c/msk_s6_c_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Schwierige Textaufgaben bearbeiten
	 - b) Ergänze den Prozentstreifen zu dieser Aufgabe. Berechne und fülle die Lücke aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s6_c_5.zip](../oer/edition-1/V01/9.9.0/msk_s6_c/msk_s6_c_5/msk_s6_c_5.zip) 
:::
<hr noshade/>

