---
title: "N6C - MULTIPLIZIEREN UND DIVIDIEREN"
---

*Ich kann sicher dividieren und Rechenwege erklären* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n6_c 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1) und 1a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Divisions-Aufgaben mit Punktefeldern lösen
	 - a) (1) Rechne die Aufgaben aus. Zeichne ein passendes Bild zu der Aufgabe in das Punktefeld.
	 - a) (2) Rechne die Aufgaben aus. Zeichne ein passendes Bild zu der Aufgabe in das Punktefeld.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_c_1.zip](../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_1/msk_n6_c_1.zip) 
:::
<hr noshade/>

### 1b (1) und 1b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Divisions-Aufgaben mit Punktefeldern lösen
	 - b) (1) Rechne die Aufgaben aus. Zeichne ein passendes Bild zu der Aufgabe in das Punktefeld.
	 - b) (2) Rechne die Aufgaben aus. Zeichne ein passendes Bild zu der Aufgabe in das Punktefeld.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_c_2.zip](../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_2/msk_n6_c_2.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2), 2b (1) und 2b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Rechenwege bei Divisions-Aufgaben
	 - a) (1)
	 - a) (2)
	 - b) (1)
	 - b) (2)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_c_3.zip](../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_3/msk_n6_c_3.zip) 
:::
<hr noshade/>

### 2c (1) und 2c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Rechenwege bei Divisions-Aufgaben
	 - c) (1)
	 - c) (2)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_c_4.zip](../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_4/msk_n6_c_4.zip) 
:::
<hr noshade/>

### 3a (1), 3a (2), 3b (1) und 3b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Rechenwege bei Divisions-Aufgaben mit Rest
	 - a) (1)
	 - a) (2)
	 - b) (1)
	 - b) (2)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_c_5.zip](../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_5/msk_n6_c_5.zip) 
:::
<hr noshade/>

### 3c (1) und 3c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Rechenwege bei Divisions-Aufgaben mit Rest
	 - c) (1)
	 - c) (2)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_c_6.zip](../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_6/msk_n6_c_6.zip) 
:::
<hr noshade/>

### 4 (1), 4 (2) und 4 (3)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_7/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Verschiedene Rechenwege bei Divisions-Aufgaben
	 - NA
	 - Vergleiche deinen und Jonas Rechenweg: Was ist gleich? Was ist verschieden?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n6_c_7.zip](../oer/edition-1/V01/9.9.0/msk_n6_c/msk_n6_c_7/msk_n6_c_7.zip) 
:::
<hr noshade/>

