---
title: "D2A - DEZIMALZAHLEN ORDNEN UND VERGLEICHEN"
---

*Ich kann zu Dezimalzahlen Nachbarzahlen angeben und in Schritten zählen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_d2_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1), 1a (2), 1a (3) und 1a (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d2_a/msk_d2_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Nachbarzahlen
	 - a) (1) Zwischen welchen beiden Zahlen ohne Nachkommastelle steht die Zahl in der Mitte? Trage ein.
	 - a) (2) Zwischen welchen beiden Zahlen ohne Nachkommastelle steht die Zahl in der Mitte? Trage ein.
	 - a) (3) Zwischen welchen beiden Zahlen ohne Nachkommastelle steht die Zahl in der Mitte? Trage ein.
	 - a) (4) Zwischen welchen beiden Zahlen ohne Nachkommastelle steht die Zahl in der Mitte? Trage ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d2_a_1.zip](../oer/edition-1/V01/9.9.0/msk_d2_a/msk_d2_a_1/msk_d2_a_1.zip) 
:::
<hr noshade/>

### 1b (1), 1b (2), 1b (3) und 1b (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d2_a/msk_d2_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Nachbarzahlen
	 - b) (1) Zwischen welchen beiden Zahlen einer Nachkommastelle steht die Zahl in der Mitte? Trage ein.
	 - b) (2) Zwischen welchen beiden Zahlen einer Nachkommastelle steht die Zahl in der Mitte? Trage ein.
	 - b) (3) Zwischen welchen beiden Zahlen einer Nachkommastelle steht die Zahl in der Mitte? Trage ein.
	 - b) (4) Zwischen welchen beiden Zahlen einer Nachkommastelle steht die Zahl in der Mitte? Trage ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d2_a_2.zip](../oer/edition-1/V01/9.9.0/msk_d2_a/msk_d2_a_2/msk_d2_a_2.zip) 
:::
<hr noshade/>

### 2a und 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d2_a/msk_d2_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 In Schritten vorwärts und rückwärts zählen
	 - a) Zähle von 5,4 in Einer-Schritten vorwärts und rückwärts. Fülle die leeren Kästchen aus.
	 - b) Zähle von 2,7 in Einer-Schritten vorwärts und rückwärts. Fülle die leeren Kästchen aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d2_a_3.zip](../oer/edition-1/V01/9.9.0/msk_d2_a/msk_d2_a_3/msk_d2_a_3.zip) 
:::
<hr noshade/>

### 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d2_a/msk_d2_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 In Schritten vorwärts und rückwärts zählen
	 - c) Zähle von 0,4 in 0,2er Schritten vorwärts. Fülle die leeren Kästchen aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d2_a_4.zip](../oer/edition-1/V01/9.9.0/msk_d2_a/msk_d2_a_4/msk_d2_a_4.zip) 
:::
<hr noshade/>

### 2d (1) und 2d (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d2_a/msk_d2_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 In Schritten vorwärts und rückwärts zählen
	 - d) (1) Fülle die leeren Kästchen aus. Schreibe auf, in welchen Schritten gezählt wird.
	 - d) (2) Fülle die leeren Kästchen aus. Schreibe auf, in welchen Schritten gezählt wird.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d2_a_5.zip](../oer/edition-1/V01/9.9.0/msk_d2_a/msk_d2_a_5/msk_d2_a_5.zip) 
:::
<hr noshade/>

