---
title: "B1C - BRÜCHE UND PROZENTE VERSTEHEN"
---

*Ich kann Anteile von Mengen bestimmen und darstellen * 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_b1_c 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1) und 1a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Anteile von Mengen bestimmen
	 - a) (1) Wie viele Kinder sind das? Schreibe die Zahl auf.
	 - a) (2) Wie viele Kinder sind das? Schreibe die Zahl auf.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_c_1.zip](../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_1/msk_b1_c_1.zip) 
:::
<hr noshade/>

### 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Anteile von Mengen bestimmen
	 - b) Wie viele Kinder sind 2/3 von 12 Kindern? Zeige mit einem Bild. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_c_2.zip](../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_2/msk_b1_c_2.zip) 
:::
<hr noshade/>

### 1c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Anteile von Mengen bestimmen
	 - c) Wie viele Kinder sind 5/6 von 18 Kindern? Zeige mit einem Bild. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_c_3.zip](../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_3/msk_b1_c_3.zip) 
:::
<hr noshade/>

### 1d
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Anteile von Mengen bestimmen
	 - d) Wie viele Kinder sind 3/4 von 12 Kindern? Wähle das passende Punktebild aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_c_4.zip](../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_4/msk_b1_c_4.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2), 2a (3) und 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Anteile von Mengen berechnen
	 - a) (1) Wie viele Bonbons sind das? Berechne ohne Bild.
	 - a) (2) Wie viele Bonbons sind das? Berechne ohne Bild.
	 - a) (3) Wie viele Bonbons sind das? Berechne ohne Bild.
	 - b) Erkläre deine Rechnung zu a) (3).
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_c_5.zip](../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_5/msk_b1_c_5.zip) 
:::
<hr noshade/>

### 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Anteile von Mengen berechnen
	 - c) Schreibe den Anteil für die Bonbons auf:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_c_6.zip](../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_6/msk_b1_c_6.zip) 
:::
<hr noshade/>

### 2d
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_7/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Anteile von Mengen berechnen
	 - d) Welche Rechnung passt zur Aufgabe 5/6 von 60 Bonbons? Wähle aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_c_7.zip](../oer/edition-1/V01/9.9.0/msk_b1_c/msk_b1_c_7/msk_b1_c_7.zip) 
:::
<hr noshade/>

