---
title: "B2A - GLEICHWERTIGKEIT VERSTEHEN"
---

*Ich kann gleichwertige Anteile in Bildern und Situationen finden * 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_b2_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a und 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_a/msk_b2_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Gleich große Anteile in Bruchstreifen finden
	 - a) Zeichne in jeden Streifen einen Anteil ein, der genauso groß ist wie 6/8.
	 - b) Beschreibe wie du den letzten Anteil gefunden hast. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_a_1.zip](../oer/edition-1/V01/9.9.0/msk_b2_a/msk_b2_a_1/msk_b2_a_1.zip) 
:::
<hr noshade/>

### 1c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_a/msk_b2_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Gleich große Anteile in Bruchstreifen finden
	 - c) Ist Stefans Behauptung wahr oder falsch? Wähle aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_a_2.zip](../oer/edition-1/V01/9.9.0/msk_b2_a/msk_b2_a_2/msk_b2_a_2.zip) 
:::
<hr noshade/>

### 2a (1) und 2a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_a/msk_b2_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Gleich große Anteile mit und ohne Streifen finden
	 - a) (1) Gib zwei Brüche an, die genauso groß sind wie 2/5:
	 - a (2) Erklärung: (z.B. ein Bild oder eine Situation):
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_a_3.zip](../oer/edition-1/V01/9.9.0/msk_b2_a/msk_b2_a_3/msk_b2_a_3.zip) 
:::
<hr noshade/>

### 2b (1) und 2b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_a/msk_b2_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Gleich große Anteile mit und ohne Streifen finden
	 - b) (1) Leas Kuchen hat 8 Stücke. Sie isst 4 Stücke davon. Pauls Kuchen ist genauso groß, hat aber 18 kleine Stücke. Paul ist denselben Anteil vom Kuchen wie Lea. Wie viele Stücke von den 18 Stücken hat er also gegessen?
	 - b (2) Erklärung: (z.B. ein Bild):
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_a_4.zip](../oer/edition-1/V01/9.9.0/msk_b2_a/msk_b2_a_4/msk_b2_a_4.zip) 
:::
<hr noshade/>

### 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_a/msk_b2_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Gleich große Anteile mit und ohne Streifen finden
	 - c) Marcs Pizza hat 12 Stücke. Er isst 3 Stücke davon. Luisas Pizza ist genauso groß, hat aber 16 kleinere Stücke. Luisa ist denselben Anteil von der Pizza wie Marc. Wie viele Stücke von den 16 Stücken hat sie also gegessen? Wähle aus. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_a_5.zip](../oer/edition-1/V01/9.9.0/msk_b2_a/msk_b2_a_5/msk_b2_a_5.zip) 
:::
<hr noshade/>

