---
title: "D2B - DEZIMALZAHLEN ORDNEN UND VERGLEICHEN"
---

*Ich kann Dezimalzahlen vergleichen und der Größe nach ordnen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_d2_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1), 1a (2) und 1a (3)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d2_b/msk_d2_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Dezimalzahlen vergleichen und der Größe nach ordnen
	 - a) (1) Welche der beiden Zahlen 3,6 und 3,12 ist größer? Trage ein und erkläre, woran du das erkennst. 
	 - a) (2) Welche der beiden Zahlen 3,6 und 3,12 ist größer? Trage ein und erkläre, woran du das erkennst. 
	 - a) (3) Welche der beiden Zahlen 3,6 und 3,12 ist größer? Trage ein und erkläre, woran du das erkennst. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d2_b_1.zip](../oer/edition-1/V01/9.9.0/msk_d2_b/msk_d2_b_1/msk_d2_b_1.zip) 
:::
<hr noshade/>

### 1b 
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d2_b/msk_d2_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Dezimalzahlen vergleichen und der Größe nach ordnen
	 - b) (1) Vergleich die Zahlen und setze ein: <,> oder =.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d2_b_2.zip](../oer/edition-1/V01/9.9.0/msk_d2_b/msk_d2_b_2/msk_d2_b_2.zip) 
:::
<hr noshade/>

### 1c (1) und 1c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d2_b/msk_d2_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Dezimalzahlen vergleichen und der Größe nach ordnen
	 - c) (1) Trage das richtige Zeichen ein: <,> oder =. Erkläre, woran du erkennst, welche Zahl größer ist.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d2_b_3.zip](../oer/edition-1/V01/9.9.0/msk_d2_b/msk_d2_b_3/msk_d2_b_3.zip) 
:::
<hr noshade/>

### 1d (1), 1d (2) und 1d (3)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d2_b/msk_d2_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Dezimalzahlen vergleichen und der Größe nach ordnen
	 - d) (1) Stimmt die Aussage? Wähle aus.
	 - d) (2) Stimmt die Aussage? Wähle aus.
	 - d) (3) Stimmt die Aussage? Wähle aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d2_b_4.zip](../oer/edition-1/V01/9.9.0/msk_d2_b/msk_d2_b_4/msk_d2_b_4.zip) 
:::
<hr noshade/>

### 1e
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d2_b/msk_d2_b_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Dezimalzahlen vergleichen und der Größe nach ordnen
	 - e) Ordne die Zahlen der Größe nach. Beginne mit der Kleinsten. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d2_b_5.zip](../oer/edition-1/V01/9.9.0/msk_d2_b/msk_d2_b_5/msk_d2_b_5.zip) 
:::
<hr noshade/>

