---
title: "D4B - MULTIPLIZIEREN UND DIVIDIEREN VON DEZIMALZAHLEN"
---

*Kann ich Dezimalzahlen mit natürlichen Zahlen multiplizieren und dividieren?* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_d4_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d4_b/msk_d4_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Dezimalzaheln mit natürlichen Zahlen multiplizieren 
	 - a) Welche Multiplikationsaufgabe passt zu dem Bild am Zahlenstrahl?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d4_b_1.zip](../oer/edition-1/V01/9.9.0/msk_d4_b/msk_d4_b_1/msk_d4_b_1.zip) 
:::
<hr noshade/>

### 1b (1)(1), 1b (1)(2), 1b (2)(1) und 1b (2)(2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d4_b/msk_d4_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Dezimalzaheln mit natürlichen Zahlen multiplizieren
	 - b) Rechne aus und erkläre, wie du gerechnet hast.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d4_b_2.zip](../oer/edition-1/V01/9.9.0/msk_d4_b/msk_d4_b_2/msk_d4_b_2.zip) 
:::
<hr noshade/>

### 1b (1)(1), 1b (1)(2), 1b (2)(1) und 1b (2)(2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d4_b/msk_d4_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1Dezimalzaheln mit natürlichen Zahlen multiplizieren
	 - b) Rechne aus und erkläre, wie du gerechnet hast.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d4_b_2.zip](../oer/edition-1/V01/9.9.0/msk_d4_b/msk_d4_b_2/msk_d4_b_2.zip) 
:::
<hr noshade/>

### 2a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d4_b/msk_d4_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Deizimalzahlen durch natürliche Zahlen dividieren und umgekehrt
	 - a) Welche Dividionsaufgabe passt zu den Bild am Zahlenstrahl?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d4_b_3.zip](../oer/edition-1/V01/9.9.0/msk_d4_b/msk_d4_b_3/msk_d4_b_3.zip) 
:::
<hr noshade/>

### 2b (1)(1), 2b (1)(2), 2b (2)(1), 2b (2)(2), 2b (3)(1) und 2b (3)(2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d4_b/msk_d4_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Deizimalzahlen durch natürliche Zahlen dividieren und umgekehrt
	 - b) Rechne aus und erkläre, wie du gerechnet hast.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d4_b_4.zip](../oer/edition-1/V01/9.9.0/msk_d4_b/msk_d4_b_4/msk_d4_b_4.zip) 
:::
<hr noshade/>

