---
title: "N4B - MULTIPLIKATION UND DIVISION VERSTEHEN"
---

*Ich kann Divisions-Aufgaben zu Situationen finden und umgekehrt* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n4_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a und 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Mit Division gerecht verteilen
	 - a) Drei Kinder teilen sich 12 Bonbons. 
Jedes Kind bekommt gleich viele.
Wie viele Bonbons bekommt jedes Kind?
Schreibe eine passende Geteilt-Aufgabe auf:
	 - b) Zeichne ein passendes Bild:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_1.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_1/msk_n4_b_1.zip) 
:::
<hr noshade/>

### 5a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_10/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 5 Division am Zahlenstrahl
	 - a) Schreibe zu den Sprüngen auf dem Zahlenstrahl eine passende Geteilt-Aufgabe auf.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_10.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_10/msk_n4_b_10.zip) 
:::
<hr noshade/>

### 5b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_11/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 5 Division am Zahlenstrahl
	 - b) Zeichne auf dem Zahlenstrahl passende Sprünge zu der Geteilt-Aufgabe 20:5.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_11.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_11/msk_n4_b_11.zip) 
:::
<hr noshade/>

### 5c (1) und 5c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_12/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 5 Division am Zahlenstrahl
	 - c) Sebastian hat zu der Geteilt-Aufgabe 15:5=3 diese Sprünge auf dem Zahlenstrahl gezeichnet:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_12.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_12/msk_n4_b_12.zip) 
:::
<hr noshade/>

### 5d (1) und 5d (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_13/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 5 Division am Zahlenstrahl
	 - d) Ali hat zu der Geteilt-Aufgabe 21:3=7 diese Sprünge auf dem Zahlenstrahl gezeichnet:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_13.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_13/msk_n4_b_13.zip) 
:::
<hr noshade/>

### 2a (1) und 2a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Divisions-Aufgaben zu Punktebildern
	 - a) Anna hat dieses Bild zu der Geteilt-Aufgabe 9:3=3 gezeichnet:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_2.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_2/msk_n4_b_2.zip) 
:::
<hr noshade/>

### 2b (1) und 2b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Divisions-Aufgaben zu Punktebildern
	 - b) Mats hat dieses Bild zu der Geteilt-Aufgabe 8:4=2 gezeichnet:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_3.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_3/msk_n4_b_3.zip) 
:::
<hr noshade/>

### 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Divisions-Aufgaben zu Punktebildern
	 - NA
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_4.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_4/msk_n4_b_4.zip) 
:::
<hr noshade/>

### 3
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Mit Division gleichmäßig aufteilen
	 - Immer 5 Gummibärchen sollen in eine Tüte.
Wie viele Tüten braucht man?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_5.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_5/msk_n4_b_5.zip) 
:::
<hr noshade/>

### 4a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Division und Rechengeschichten
	 - NA
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_6.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_6/msk_n4_b_6.zip) 
:::
<hr noshade/>

### 4b (1) und 4b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_7/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Division und Rechengeschichten
	 - b) Lucia hat diese Textaufgabe zu der Geteilt-Aufgabe 27:9=3 geschrieben:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_7.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_7/msk_n4_b_7.zip) 
:::
<hr noshade/>

### 4c (1) und 4c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_8/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Division und Rechengeschichten
	 - c) Jakob hat diese Textaufgabe zu der Geteilt-Aufgabe 24:6=4 geschrieben:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_8.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_8/msk_n4_b_8.zip) 
:::
<hr noshade/>

### 4d (1) und 4d (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_9/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Division und Rechengeschichten
	 - d) Lea hat diese Textaufgabe zu der Geteilt-Aufgabe 24:6=4 geschrieben:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n4_b_9.zip](../oer/edition-1/V01/9.9.0/msk_n4_b/msk_n4_b_9/msk_n4_b_9.zip) 
:::
<hr noshade/>

