---
title: "B1B - BRÜCHE UND PROZENTE VERSTEHEN"
---

*Ich kann Prozente bestimmen und darstellen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_b1_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_b/msk_b1_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Prozente in Bruchstreifen bestimmen und darstellen
	 - a) Schreibe als Prozent:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_b_1.zip](../oer/edition-1/V01/9.9.0/msk_b1_b/msk_b1_b_1/msk_b1_b_1.zip) 
:::
<hr noshade/>

### 1b (1) und 1b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_b/msk_b1_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Prozente in Bruchstreifen bestimmen und darstellen
	 - b) (1) Lies ab, wie viel Prozent vom Streifen gefärbt sind. Gib auch den Anteil an.
	 - b) (2) Lies ab, wie viel Prozent vom Streifen gefärbt sind. Gib auch den Anteil an.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_b_2.zip](../oer/edition-1/V01/9.9.0/msk_b1_b/msk_b1_b_2/msk_b1_b_2.zip) 
:::
<hr noshade/>

### 1c (1) und 1c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_b/msk_b1_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Prozente in Bruchstreifen bestimmen und darstellen
	 - c) (1) Zeichne die Prozente farbig ein. Gib auch den Anteil an. 
	 - c) (2) Zeichne die Prozente farbig ein. Gib auch den Anteil an. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_b_3.zip](../oer/edition-1/V01/9.9.0/msk_b1_b/msk_b1_b_3/msk_b1_b_3.zip) 
:::
<hr noshade/>

### 1d (1) und 1d (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b1_b/msk_b1_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Prozente in Bruchstreifen bestimmen und darstellen
	 - d) (1) Zeichne den Anteil farbig ein. Gib auch die Prozentzahl an. 
	 - d) (2) Zeichne den Anteil farbig ein. Gib auch die Prozentzahl an. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_b_4.zip](../oer/edition-1/V01/9.9.0/msk_b1_b/msk_b1_b_4/msk_b1_b_4.zip) 
:::
<hr noshade/>

