---
title: "S1B - LÄNGEN UND FLÄCHENINHALTE VERSTEHEN"
---

*Ich kann mir Beziehungen zwischen Längen und Flächeninhalten vorstellen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s1_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a und 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_b/msk_s1_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Flächen vergleichen und ausmessen
	 - a) Kreuze das Quadrat an, das die größte graue Fläche hat.
	 - b) Beschreibe, wie du bei der Lösung vorgegangen bist.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_b_1.zip](../oer/edition-1/V01/9.9.0/msk_s1_b/msk_s1_b_1/msk_s1_b_1.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2), 2a (3) und 2a (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_b/msk_s1_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Flächenmaße kennen und berechnen
	 - a) (1) Wähle das richtige Flächenmaß aus: cm oder cm² oder m oder m² oder km oder km².
	 - a) (2) Wähle das richtige Flächenmaß aus: cm oder cm² oder m oder m² oder km oder km².
	 - a) (3) Wähle das richtige Flächenmaß aus: cm oder cm² oder m oder m² oder km oder km².
	 - a) (4) Wähle das richtige Flächenmaß aus: cm oder cm² oder m oder m² oder km oder km².
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_b_2.zip](../oer/edition-1/V01/9.9.0/msk_s1_b/msk_s1_b_2/msk_s1_b_2.zip) 
:::
<hr noshade/>

### 2b 
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_b/msk_s1_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Flächenmaße kennen und berechnen
	 - b) Wie groß sind die grauen Flächen? Gib die Anzahl der Kästchen und die cm² an.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_b_3.zip](../oer/edition-1/V01/9.9.0/msk_s1_b/msk_s1_b_3/msk_s1_b_3.zip) 
:::
<hr noshade/>

### 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_b/msk_s1_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Flächenmaße kennen und berechnen
	 - c) Leonies Zimmer ist 4m lang und 3m breit. Wie groß ist die Fläche ihres Fußbodens? Schreibe oder zeichne deinen Lösungsweg und dein Ergebnis auf.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_b_4.zip](../oer/edition-1/V01/9.9.0/msk_s1_b/msk_s1_b_4/msk_s1_b_4.zip) 
:::
<hr noshade/>

