---
title: "D1A - STELLENWERTE VON DEZIMALZAHLEN VERSTEHEN"
---

*Ich kann Stellenwerte von Dezimalzahlen verstehen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_d1_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a und 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Dezimalzahlen am Zahlenstrahl
	 - a) Markiere im Zahlenstrahl und schreibe die richtigen Zahlen in Kästchen
	 - b) Markiere im Zahlenstrahl und schreibe die richtigen Zahlen in Kästchen
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d1_a_1.zip](../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_1/msk_d1_a_1.zip) 
:::
<hr noshade/>

### 1c (1) und 1c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Dezimalzahlen am Zahlenstrahl
	 - c) Kreuze an. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d1_a_2.zip](../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_2/msk_d1_a_2.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2), 2a (3), 2a (4), 2a (5), 2a (6) und 2a (7)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Dezimalzahlen in der Stellentafel
	 - a) (1) Fülle zuerst die grauen Kästchen aus. Schreibe dann als Dezimalzahl und in die Stellentafel. 
	 - a) (2) Fülle zuerst die grauen Kästchen aus. Schreibe dann als Dezimalzahl und in die Stellentafel. 
	 - a) (3) Fülle zuerst die grauen Kästchen aus. Schreibe dann als Dezimalzahl und in die Stellentafel. 
	 - a) (4) Fülle zuerst die grauen Kästchen aus. Schreibe dann als Dezimalzahl und in die Stellentafel. 
	 - a) (5) Fülle zuerst die grauen Kästchen aus. Schreibe dann als Dezimalzahl und in die Stellentafel. 
	 - a) (6) Fülle zuerst die grauen Kästchen aus. Schreibe dann als Dezimalzahl und in die Stellentafel. 
	 - a) (7) Fülle zuerst die grauen Kästchen aus. Schreibe dann als Dezimalzahl und in die Stellentafel. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d1_a_3.zip](../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_3/msk_d1_a_3.zip) 
:::
<hr noshade/>

### 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Dezimalzahlen in der Stellentafel
	 - b) Markiere die Hundertstel.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d1_a_4.zip](../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_4/msk_d1_a_4.zip) 
:::
<hr noshade/>

### 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Dezimalzahlen in der Stellentafel
	 - c) Ist 2,4 genauso viel wie 2 Einer und 4 Hundertstel?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d1_a_5.zip](../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_5/msk_d1_a_5.zip) 
:::
<hr noshade/>

### 2d
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Dezimalzahlen in der Stellentafel
	 - d) Wähle die richtige Zahl aus. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d1_a_6.zip](../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_6/msk_d1_a_6.zip) 
:::
<hr noshade/>

### 3
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_7/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Zahlen immer feiner darstellen
	 - Welche Zahlen stehen dazwischen? Ordne zu. Einige Zahlen der unteren Zeile können mehrfach zugeordnet werden.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_d1_a_7.zip](../oer/edition-1/V01/9.9.0/msk_d1_a/msk_d1_a_7/msk_d1_a_7.zip) 
:::
<hr noshade/>

