---
title: "N2B - ZAHLEN ORDNEN UND VERGLEICHEN"
---

*Ich kann Zahlen miteinander vergleichen und der Größe nach ordnen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n2_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a, 1b, 1c und 1d
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_b/msk_n2_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Zahlen einordnen
	 - a) Finde die Mitte zwischen:
	 - b) Finde die Mitte zwischen:
	 - c) Finde die Mitte zwischen:
	 - d) Finde die Mitte zwischen:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_b_1.zip](../oer/edition-1/V01/9.9.0/msk_n2_b/msk_n2_b_1/msk_n2_b_1.zip) 
:::
<hr noshade/>

### 2a, 2b und 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_b/msk_n2_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Zahlen vergleichen
	 - a) Vergleiche: "Kleiner als (<) " oder "größer als (>)"? Trage ein.
	 - b) Vergleiche: "Kleiner als (<) " oder "größer als (>)"? Trage ein.
	 - c) Vergleiche: "Kleiner als (<) " oder "größer als (>)"? Trage ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_b_2.zip](../oer/edition-1/V01/9.9.0/msk_n2_b/msk_n2_b_2/msk_n2_b_2.zip) 
:::
<hr noshade/>

### 3a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_b/msk_n2_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Zahlen der Größe nach ordnen
	 - a) Ordne die Zahlen nach ihrer Größe. Beginne mit der kleinsten Zahl.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_b_3.zip](../oer/edition-1/V01/9.9.0/msk_n2_b/msk_n2_b_3/msk_n2_b_3.zip) 
:::
<hr noshade/>

### 3b (1) und 3b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_b/msk_n2_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Zahlen der Größe nach ordnen
	 - b) (1) Bilde aus den Ziffern 2, 5, 8, 9,3 die größte und die kleinste fünfstellige Zahl:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_b_4.zip](../oer/edition-1/V01/9.9.0/msk_n2_b/msk_n2_b_4/msk_n2_b_4.zip) 
:::
<hr noshade/>

