---
title: "N2A - ZAHLEN ORDNEN UND VERGLEICHEN"
---

*Ich kann Zahlen am Zahlenstrahl lesen und darstellen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n2_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a und 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_a/msk_n2_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Zahlen an der Hunderterkette
	 - a) Trage die passenden Zahlen ein.
	 - b) Verbinde die Karten mit den richtigen Stellen an der Hunderterkette. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_a_1.zip](../oer/edition-1/V01/9.9.0/msk_n2_a/msk_n2_a_1/msk_n2_a_1.zip) 
:::
<hr noshade/>

### 2a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_a/msk_n2_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Zahlen am Zahlenstrahl
	 - a) Trage passende Zahlen ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_a_2.zip](../oer/edition-1/V01/9.9.0/msk_n2_a/msk_n2_a_2/msk_n2_a_2.zip) 
:::
<hr noshade/>

### 2b und 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_a/msk_n2_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Zahlen am Zahlenstrahl
	 - b) Verbinde die Karten mit den richtigen Stellen auf dem Zahlenstrahl.
	 - c) Beschreibe, wie du die richtige Stelle für die Zahl 99 am Zahlenstrahl gefunden hast. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_a_3.zip](../oer/edition-1/V01/9.9.0/msk_n2_a/msk_n2_a_3/msk_n2_a_3.zip) 
:::
<hr noshade/>

### 3a und 3b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n2_a/msk_n2_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Skalierungen am Zahlenstrahl
	 - a) Trage die passenden Zahlen auf dem Tausenderstrahl ein.
	 - b) Verbinde die Karten mit den richtigen Stellen auf dem Tausenderstrahl.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n2_a_4.zip](../oer/edition-1/V01/9.9.0/msk_n2_a/msk_n2_a_4/msk_n2_a_4.zip) 
:::
<hr noshade/>

