---
title: "S6B - MIT PROZENTEN RECHNEN"
---

*Ich kann flexibel Grundwerte abschätzen und bestimmen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s6_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s6_b/msk_s6_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Grundwerte am Streifen finden
	 - Das Handy hat schon 8 MB einer App heruntergeladen. Das sind 20 % der gesamten App. Wie viel MB ist die ganze App groß? Schätze ungefähr. Stelle die Situation am Streifen dar.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s6_b_1.zip](../oer/edition-1/V01/9.9.0/msk_s6_b/msk_s6_b_1/msk_s6_b_1.zip) 
:::
<hr noshade/>

### 2a und 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s6_b/msk_s6_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Grundwerte bestimmen
	 - a) Eine Jeans kostet jetzt 48 €. Das sind 80 % vom alten Preis. Wie teuer war die Jeans vorher? Finde den fehlenden Wert.
	 - b) Erkläre, wie du in a) den alten Preis gefunden hast.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s6_b_2.zip](../oer/edition-1/V01/9.9.0/msk_s6_b/msk_s6_b_2/msk_s6_b_2.zip) 
:::
<hr noshade/>

### 2c und 2d
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s6_b/msk_s6_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Prozentwerte und Prozentsätze am Streifen finden
	 - c) Fülle die Lücken aus!
	 - d) Erkläre deine Lösung zu c) (1). Zeichne am Streifen ein.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s6_b_3.zip](../oer/edition-1/V01/9.9.0/msk_s6_b/msk_s6_b_3/msk_s6_b_3.zip) 
:::
<hr noshade/>

### 3a, 3b (1) und 3b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s6_b/msk_s6_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Umgang mit Verminderungen
	 - a) In einem Geschäft sind alle Pullover um 30 % herabgesetzt. Ein Pullover kostet nun 42 €. Wie teuer war der Pullover vorher? Zeichne am Streifen ein.
	 - b) Ergänze die Aussagen zu der Situation aus a).
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s6_b_4.zip](../oer/edition-1/V01/9.9.0/msk_s6_b/msk_s6_b_4/msk_s6_b_4.zip) 
:::
<hr noshade/>

