---
title: "N7B - SCHRIFTLICH ADDIEREN UND SUBTRAHIEREN"
---

*Ich kann schriftlich subtrahieren und das Rechenverfahren erklären* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n7_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a und 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_b/msk_n7_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Subtraktion ohne Übertrag
	 - a)
	 - b)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_b_1.zip](../oer/edition-1/V01/9.9.0/msk_n7_b/msk_n7_b_1/msk_n7_b_1.zip) 
:::
<hr noshade/>

### 2a, 2b und 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_b/msk_n7_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Subtraktion mit Übertrag
	 - a)
	 - b)
	 - c)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_b_2.zip](../oer/edition-1/V01/9.9.0/msk_n7_b/msk_n7_b_2/msk_n7_b_2.zip) 
:::
<hr noshade/>

### 3a, 3b und 3c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_b/msk_n7_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Subtraktion mit der Null
	 - a)
	 - b)
	 - c)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_b_3.zip](../oer/edition-1/V01/9.9.0/msk_n7_b/msk_n7_b_3/msk_n7_b_3.zip) 
:::
<hr noshade/>

### 4a (1), 4a (2), 4b (1) und 4b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n7_b/msk_n7_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 4 Subtraktion mit unterschiedlicher Stellenzahl
	 - a) (1) Rechne schriftlich untereinander.
	 - a) (2) Rechne schriftlich untereinander.
	 - b) (1) Rechne schriftlich untereinander.
	 - b) (2) Rechne schriftlich untereinander.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n7_b_4.zip](../oer/edition-1/V01/9.9.0/msk_n7_b/msk_n7_b_4/msk_n7_b_4.zip) 
:::
<hr noshade/>

