---
title: "N8A - SCHRIFTLICH MULTIPLIZIEREN"
---

*Ich kann schriftlich multiplizieren und das Rechenverfahren erklären* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_n8_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1), 1a (2), 1b (1) und 1b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Multiplikation ohne Übertrag
	 - a) (1)
	 - a) (2)
	 - b) (1)
	 - b) (2)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n8_a_1.zip](../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_1/msk_n8_a_1.zip) 
:::
<hr noshade/>

### 1c (1) und 1c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Multiplikation ohne Übertrag
	 - c) (1)
	 - c) (2)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n8_a_2.zip](../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_2/msk_n8_a_2.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2), 2b (1) und 2b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Multiplikation mit Übertrag
	 - a) (1)
	 - a) (2)
	 - b) (1)
	 - b) (2)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n8_a_3.zip](../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_3/msk_n8_a_3.zip) 
:::
<hr noshade/>

### 2c (1) und 2c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Multiplikation mit Übertrag
	 - c) (1)
	 - c) (2)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n8_a_4.zip](../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_4/msk_n8_a_4.zip) 
:::
<hr noshade/>

### 3a (1), 3a (2), 3b (1) und 3b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Multiplikation mit Null
	 - a) (1)
	 - a) (2)
	 - b) (1)
	 - b) (2)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n8_a_5.zip](../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_5/msk_n8_a_5.zip) 
:::
<hr noshade/>

### 3c (1) und 3c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Multiplikation mit Null
	 - c) (1)
	 - c) (2)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_n8_a_6.zip](../oer/edition-1/V01/9.9.0/msk_n8_a/msk_n8_a_6/msk_n8_a_6.zip) 
:::
<hr noshade/>

