---
title: "S1C - LÄNGEN UND FLÄCHENINHALTE VERSTEHEN"
---

*Ich verfüge über Vorstellungen zu Gewichten* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s1_c 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a und 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_c/msk_s1_c_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Gewichte kennen und schätzen
	 - a) Welches Maß passt besser, um das Gewicht anzugeben? Kreuze jeweils an.
	 - b) Nenne drei Gegenstände, die 1kg schwer sind.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_c_1.zip](../oer/edition-1/V01/9.9.0/msk_s1_c/msk_s1_c_1/msk_s1_c_1.zip) 
:::
<hr noshade/>

### 1c (1) und 1c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_c/msk_s1_c_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Gewichte kennen, schätzen und messen
	 - c) (1) Welches Maß passt besser, um die Längen anzugeben? Kreuze an.
	 - c) (2) Nenne drei Gegenstände, die 1m lang, breit oder hoch sind.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_c_2.zip](../oer/edition-1/V01/9.9.0/msk_s1_c/msk_s1_c_2/msk_s1_c_2.zip) 
:::
<hr noshade/>

### 2a (1) und 2a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_c/msk_s1_c_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Gewichte vergleichen und mit Gewichten rechnen
	 - a) (1) Welches Tier hat seit seiner Geburt mehr Gewicht zugenommen?
	 - a) (2) Begründe deine Antwort.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_c_3.zip](../oer/edition-1/V01/9.9.0/msk_s1_c/msk_s1_c_3/msk_s1_c_3.zip) 
:::
<hr noshade/>

### 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s1_c/msk_s1_c_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Gewichte vergleichen und mit Gewichten rechnen
	 - b) Eine volle Dose Cola wiegt etwa 340g. Wie viel wiegt eine Palette mit 24 Dosen?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s1_c_4.zip](../oer/edition-1/V01/9.9.0/msk_s1_c/msk_s1_c_4/msk_s1_c_4.zip) 
:::
<hr noshade/>

