---
title: "S5B - PROPORTIONALITÄT VERSTEHEN"
---

*Ich kann erkennen, ob ein Zusammenhang proportional ist* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s5_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a und 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s5_b/msk_s5_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Proportionale Zusammenhänge in Tabellen erkennen
	 - a) Welche Tebellen stellen einen proportionalen zusammenhang dar? Kreuze an.
	 - b) Erkläre für die dritte Tabelle aus a) wie du herausgefunden hast, ob ein proportionaler Zusammenhang dargestellt wird oder nicht.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s5_b_1.zip](../oer/edition-1/V01/9.9.0/msk_s5_b/msk_s5_b_1/msk_s5_b_1.zip) 
:::
<hr noshade/>

### 1c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s5_b/msk_s5_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Proportionale Zusammenhänge in Tabellen erkennen
	 - c) Die folgenden Tabellen zeigen proportionale Zusammenhänge. Berechne die fehlenden Werte in den Tabellen.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s5_b_2.zip](../oer/edition-1/V01/9.9.0/msk_s5_b/msk_s5_b_2/msk_s5_b_2.zip) 
:::
<hr noshade/>

### 2a (1)(1), 2a (1)(2), 2a (2)(1) und 2a (2)(2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s5_b/msk_s5_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Proportionale Zusammenhänge in Situationen erkennen
	 - a) Prüfe, ob die Aufgaben proportionale Zusammenhänge zeigen und löse sie.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s5_b_3.zip](../oer/edition-1/V01/9.9.0/msk_s5_b/msk_s5_b_3/msk_s5_b_3.zip) 
:::
<hr noshade/>

### 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s5_b/msk_s5_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Proportionale Zusammenhänge in Situationen erkennen
	 - b) Woran erkennst du in einer Aufgabe, ob ein proportionaler zusammenhang dargestellt wird. Erkläre.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s5_b_4.zip](../oer/edition-1/V01/9.9.0/msk_s5_b/msk_s5_b_4/msk_s5_b_4.zip) 
:::
<hr noshade/>

