---
title: "B4A - MIT BRÜCHEN RECHNEN"
---

*Ich kann Addition und Subtraktion von Brüchen verstehen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_b4_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1), 1a (2) und 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b4_a/msk_b4_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Anteil mit gleichen Nennern zusammenfügen und wegnehmen 
	 - Rechne aus:
	 - Rechnung:
	 - Erkläre deine Rechnung mit einem Bild:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b4_a_1.zip](../oer/edition-1/V01/9.9.0/msk_b4_a/msk_b4_a_1/msk_b4_a_1.zip) 
:::
<hr noshade/>

### 1c (1) und 1c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b4_a/msk_b4_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Anteil mit gleichen Nennern zusammenfügen und wegnehmen 
	 - Rechne aus:
	 - Rechnung:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b4_a_2.zip](../oer/edition-1/V01/9.9.0/msk_b4_a/msk_b4_a_2/msk_b4_a_2.zip) 
:::
<hr noshade/>

### 2a (1)(1), 2a (1)(2), 2a (2)(1), 2a (2)(2), 2a (3)(1) und 2a (3)(2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b4_a/msk_b4_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Anteil mit verschiedenen Nennern zusammenfügen und wegnehmen 
	 - Rechne aus: (1)
	 - Ich rechne so:
	 - Rechne aus: (2)
	 - Rechne aus: (3)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b4_a_3.zip](../oer/edition-1/V01/9.9.0/msk_b4_a/msk_b4_a_3/msk_b4_a_3.zip) 
:::
<hr noshade/>

### 2b (1)(1), 2b (1)(2), 2b (2)(1), 2b (2)(2), 2b (3)(1) und 2b (3)(2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b4_a/msk_b4_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Anteil mit verschiedenen Nennern zusammenfügen und wegnehmen 
	 - Rechne aus: (1)
	 - Ich rechne so:
	 - Rechne aus: (2)
	 - Rechne aus: (3)
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b4_a_4.zip](../oer/edition-1/V01/9.9.0/msk_b4_a/msk_b4_a_4/msk_b4_a_4.zip) 
:::
<hr noshade/>

### 3
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b4_a/msk_b4_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Addition und Subtraktion vielfältig verwenden
	 - Schreibe eine Textaufgabe, bei der man 1/2 + 1/4= 3/4 rechnen muss.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b4_a_5.zip](../oer/edition-1/V01/9.9.0/msk_b4_a/msk_b4_a_5/msk_b4_a_5.zip) 
:::
<hr noshade/>

