---
title: "S5A - PROPORTIONALITÄT VERSTEHEN"
---

*Ich kann bei proportionalen Zusammenhägen in Tabellen und im Kopf hoch- und runterrchnen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s5_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s5_a/msk_s5_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Idee: ,,Pro Portion"
	 - a) 2 Stücke kosten 1,60 €. Wie viel kostet 5 Stück? Berechne. Nutze für deine Rechnungen die Felder neben der Tabelle.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s5_a_1.zip](../oer/edition-1/V01/9.9.0/msk_s5_a/msk_s5_a_1/msk_s5_a_1.zip) 
:::
<hr noshade/>

### 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s5_a/msk_s5_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Idee: ,,Pro Portion"
	 - b) 8 kg Äpfel kosten 4 €. Wie viel kosten 12 kg Äpfel? Berechne und erkläre, wie du vorgegangen bist.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s5_a_2.zip](../oer/edition-1/V01/9.9.0/msk_s5_a/msk_s5_a_2/msk_s5_a_2.zip) 
:::
<hr noshade/>

### 2a (1) und 2a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s5_a/msk_s5_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Rechnen mit dem festen Faktor
	 - a) Berechne den Preis pro kg und erkläre, wie du vorgegangen bist.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s5_a_3.zip](../oer/edition-1/V01/9.9.0/msk_s5_a/msk_s5_a_3/msk_s5_a_3.zip) 
:::
<hr noshade/>

### 2b (1) und 2b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s5_a/msk_s5_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Rechnen mit dem festen Faktor
	 - b) (1) In der Tabelle ist ein Fehler. Ist der Preis pro Stück immer gleich? Scuhe und korrigiere. Bestimme dann den fehlenden Wert. Erkläre.
	 - b) (2) So bin ich vorgegangen.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s5_a_4.zip](../oer/edition-1/V01/9.9.0/msk_s5_a/msk_s5_a_4/msk_s5_a_4.zip) 
:::
<hr noshade/>

### 3 (1) und 3 (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s5_a/msk_s5_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Im Kopf hoch- und runterrechnen
	 - Vergleiche die Preise für die verschiedenen Birnensorten. Welche ist am günstigsten? Kreuze an und notiere deine Erklärung.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s5_a_5.zip](../oer/edition-1/V01/9.9.0/msk_s5_a/msk_s5_a_5/msk_s5_a_5.zip) 
:::
<hr noshade/>

