---
title: "DB - ZUSAMMENHANG VON DEZIMALZAHLEN UND BRÜCHEN"
---

*Ich kann einfache Dezimalzahlen und Brüche ineinander umwandeln* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_db 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1), 1a (2), 1a (3) und 1a (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_db/msk_db_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Zehnerbrüche und Dezimalzahlen ineinander umwandeln
	 - a) (1) Schreibe als Dezimalzahl und erkläre, wie du vorgegangen bist.
	 - a) (2) Schreibe als Dezimalzahl und erkläre, wie du vorgegangen bist.
	 - a) Erklärung zu (3):
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_db_1.zip](../oer/edition-1/V01/9.9.0/msk_db/msk_db_1/msk_db_1.zip) 
:::
<hr noshade/>

### 1b (1), 1b (2), 1b (3) und 1b (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_db/msk_db_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Zehnerbrüche und Dezimalzahlen ineinander umwandeln
	 - a) (1) Schreibe als Bruch und erkläre, wie du vorgegangen bist.
	 - a) (2) Schreibe als Bruch und erkläre, wie du vorgegangen bist.
	 - a) Erklärung zu (3):
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_db_2.zip](../oer/edition-1/V01/9.9.0/msk_db/msk_db_2/msk_db_2.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2), 2a (3) und 2a (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_db/msk_db_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Andere Brüche und Dezimalzahlen ineinander umwandeln
	 - a) (1) Schreibe als Dezimalzahl und erkläre, wie du vorgegangen bist.
	 - a) (2) Schreibe als Dezimalzahl und erkläre, wie du vorgegangen bist.
	 - a) Erklärung zu (3):
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_db_3.zip](../oer/edition-1/V01/9.9.0/msk_db/msk_db_3/msk_db_3.zip) 
:::
<hr noshade/>

