---
title: "B1A - BRÜCHE UND PROZENTE VERSTEHEN"
---

*Ich kann Anteile von einem Ganzen bestimmen und darstellen * 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_b1_a 
* Auflage: edition-1 
* Version: V02 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Ein Stück vom Ganzen bestimmen und darstellen
	 - a) Gibt den Anteil (Bruch) für den blauen Teil an.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_a_1.zip](../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_1/msk_b1_a_1.zip) 
:::
<hr noshade/>

### 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Ein Stück vom Ganzen bestimmen und darstellen
	 - b) Zeichne den Teil farbig ein, so dass der Anteil passt.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_a_2.zip](../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_2/msk_b1_a_2.zip) 
:::
<hr noshade/>

### 1c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Ein Stück vom Ganzen bestimmen und darstellen
	 - c) Welches Bild passt zu dem blauen Anteil? Wähle aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_a_3.zip](../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_3/msk_b1_a_3.zip) 
:::
<hr noshade/>

### 1d (1), 1d (2) und 1e
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Ein Stück vom Ganzen bestimmen und darstellen
	 - d) Gib den Anteil für den blauen Teil an.
	 - e) Erkläre deine Lösung zum Bild d) (2).
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_a_4.zip](../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_4/msk_b1_a_4.zip) 
:::
<hr noshade/>

### 1f
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Ein Stück vom Ganzen bestimmen und darstellen
	 - f) Welches Bild passt zu dem blauen Anteil? Wähle aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_a_5.zip](../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_5/msk_b1_a_5.zip) 
:::
<hr noshade/>

### 2a (1), 2a (2) und 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Mehrere Stücke vom Ganzen bestimmen und darstellen
	 - a) Gib jeweils den Anteil (Bruch) für den blauen Teil an.
	 - b) Erkläre deine Lösung zu Bild a) (2).
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_a_6.zip](../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_6/msk_b1_a_6.zip) 
:::
<hr noshade/>

### 2c
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_7/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Mehrere Stücke vom Ganzen bestimmen und darstellen
	 - c) Welches Bild passt zu dem blauen Anteil? Wähle aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_a_7.zip](../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_7/msk_b1_a_7.zip) 
:::
<hr noshade/>

### 2d (1) und 2d (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_8/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Mehrere Stücke vom Ganzen bestimmen und darstellen
	 - d) Zeichne für beide Bilder den Teil farbig ein, so dass der Anteil passt.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_a_8.zip](../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_8/msk_b1_a_8.zip) 
:::
<hr noshade/>

### 2e
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_9/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Mehrere Stücke vom Ganzen bestimmen und darstellen
	 - e) Welches Bild passt zu dem blauen Anteil? Wähle aus.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b1_a_9.zip](../oer/edition-1/V02/9.9.0/msk_b1_a/msk_b1_a_9/msk_b1_a_9.zip) 
:::
<hr noshade/>

