---
title: "S2B - SACHAUFGABEN LÖSEN"
---

*Ich kann Sachaufagaben mit fehlenden Informationen lösen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_s2_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s2_b/msk_s2_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Fehlende Informationen finden
	 - a) Welche Informationen braucht man, um die Aufgabe ausrechnen zu können?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s2_b_1.zip](../oer/edition-1/V01/9.9.0/msk_s2_b/msk_s2_b_1/msk_s2_b_1.zip) 
:::
<hr noshade/>

### 2a und 2b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s2_b/msk_s2_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Passende Fragen finden
	 - a) Kreuze die Fragen an, die man mit den Informationen beantworten kann.
	 - b) Schreibe eine weitere Frage auf, die man beantworten kann.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s2_b_2.zip](../oer/edition-1/V01/9.9.0/msk_s2_b/msk_s2_b_2/msk_s2_b_2.zip) 
:::
<hr noshade/>

### 3 (1), 3 (2), 3 (3) und 3 (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_s2_b/msk_s2_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 3 Einfachere Fragen stellen
	 - (1 ) Welche einfacheren Fragen können dir helfen, die Aufgabe zu lösen? Kreuze an und begründe. Du musst bei dieser Aufgabe nichts ausrechnen.
	 - (2 ) Welche einfacheren Fragen können dir helfen, die Aufgabe zu lösen? Kreuze an und begründe. Du musst bei dieser Aufgabe nichts ausrechnen.
	 - (3 ) Welche einfacheren Fragen können dir helfen, die Aufgabe zu lösen? Kreuze an und begründe. Du musst bei dieser Aufgabe nichts ausrechnen.
	 - (4 ) Welche einfacheren Fragen können dir helfen, die Aufgabe zu lösen? Kreuze an und begründe. Du musst bei dieser Aufgabe nichts ausrechnen.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_s2_b_3.zip](../oer/edition-1/V01/9.9.0/msk_s2_b/msk_s2_b_3/msk_s2_b_3.zip) 
:::
<hr noshade/>

