---
title: "B2B - GLEICHWERTIGKEIT VERSTEHEN"
---

*Ich kann gleichwertige Brüche durch Erweitern und Kürzen finden* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_b2_b 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1), 1a (2), 1b (1) und 1b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Gleichwertige Anteile im Kopf finden
	 - a) (1) Stell dir 9/12 und 3/4 in Bruchstreifen vor. Welcher Streifen hat eine feinere Einteilung, also mehr Felder? Wähle aus. 
	 - a) (2) Stell dir 9/12 und 3/4 in Bruchstreifen vor. Welcher Streifen hat eine feinere Einteilung, also mehr Felder? Wähle aus. 
	 - b) (1) Welcher Anteil ist größer 9/12 oder 3/4?
	 - b) (2) Welcher Anteil ist größer 9/12 oder 3/4?
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_b_1.zip](../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_1/msk_b2_b_1.zip) 
:::
<hr noshade/>

### 1c (1), 1c (2), 1c (3) und 1c (4)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Gleichwertige Anteile im Kopf finden
	 - c) (1) Entscheide, ob die folgenden Begründungen richtig oder falsch sind. 
	 - c) (2) Entscheide, ob die folgenden Begründungen richtig oder falsch sind. 
	 - c) (3) Entscheide, ob die folgenden Begründungen richtig oder falsch sind. 
	 - c) (4) Entscheide, ob die folgenden Begründungen richtig oder falsch sind. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_b_2.zip](../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_2/msk_b2_b_2.zip) 
:::
<hr noshade/>

### 1d (1) und 1d (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Gleichwertige Anteile im Kopf finden
	 - d) (1) Finde zwei verschiedene Brüche, die genauso groß sind wir 12/36:
	 - d) (2) Finde zwei verschiedene Brüche, die genauso groß sind wir 12/36:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_b_3.zip](../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_3/msk_b2_b_3.zip) 
:::
<hr noshade/>

### 2a (1) und 2a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Gleichwertige Brüche durch Erweitern und Kürzen finden
	 - a) (1) Erweitere den Bruch mit 7:
	 - a) (2)Kürze den Bruch mit 6:
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_b_4.zip](../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_4/msk_b2_b_4.zip) 
:::
<hr noshade/>

### 2b (1) und 2b (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_5/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Gleichwertige Brüche durch Erweitern und Kürzen finden
	 - b) (1) Erweitere die Brüche.
	 - b) (2) Erweitere die Brüche.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_b_5.zip](../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_5/msk_b2_b_5.zip) 
:::
<hr noshade/>

### 2c (1) und 2c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_6/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Gleichwertige Brüche durch Erweitern und Kürzen finden
	 - c) (1) Kürze die Brüche.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b2_b_6.zip](../oer/edition-1/V01/9.9.0/msk_b2_b/msk_b2_b_6/msk_b2_b_6.zip) 
:::
<hr noshade/>

