---
title: "B3A - BRÜCHE UND PROZENTE ORDNEN"
---

*Ich kann Brüche gleichnamig machen* 


::: {.callout-note collapse="true"  title="Bausteinversion"}


* Baustein: msk_b3_a 
* Auflage: edition-1 
* Version: V01 
* Runtime: 9.9.0 
:::

## Aufgaben


### 1a (1) und 1a (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b3_a/msk_b3_a_1/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Gleichnamige Brüche mit Streifen finden
	 - a) Schreibe 3/4 und 2/3 so auf, dass sie denselben Nenner haben, also gleichnamig sind.
	 - Erkläre, wie du den Nenner gefunden hast: 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b3_a_1.zip](../oer/edition-1/V01/9.9.0/msk_b3_a/msk_b3_a_1/msk_b3_a_1.zip) 
:::
<hr noshade/>

### 1b
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b3_a/msk_b3_a_2/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Gleichnamige Brüche mit Streifen finden
	 - b) Hat Mia die Brüche richtig umgeformt, damit sie denselben Nenner haben? Kreuze an.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b3_a_2.zip](../oer/edition-1/V01/9.9.0/msk_b3_a/msk_b3_a_2/msk_b3_a_2.zip) 
:::
<hr noshade/>

### 1c (1)(1), 1c (1)(2) und 1c (2)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b3_a/msk_b3_a_3/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 1 Gleichnamige Brüche mit Streifen finden
	 - Markiere 2/3 im 3er-Streifen.
	 - Markiere 3/4 im 4er- Streifen.
	 - Im 3er Streifen kann man 2/3 gut einzeichnen, 3/4 aber nicht. In welchem Streifen kann man beide Brüche gleichzeitig gut einzeichnen? Teile den Streifen so ein und färbe darin beide verfeinerten Anteile ein. 
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b3_a_3.zip](../oer/edition-1/V01/9.9.0/msk_b3_a/msk_b3_a_3/msk_b3_a_3.zip) 
:::
<hr noshade/>

### 2 (1), 2 (2) und 2 (3)
```{=html}
<iframe width="100%" height="480"
src="../oer/edition-1/V01/9.9.0/msk_b3_a/msk_b3_a_4/viewer.html"></iframe>
```


::: {.callout-tip collapse="true"  title="Details"}


* Aufgabenüberschrift: 2 Gleichnamige Brüche berechnen
	 - Mache die Brüche gleichnamig: Schreibe sie so, dass sie denselben Nenner haben.
* Quelldatei für CBA ItemBuilder 9.9.0: [msk_b3_a_4.zip](../oer/edition-1/V01/9.9.0/msk_b3_a/msk_b3_a_4/msk_b3_a_4.zip) 
:::
<hr noshade/>

